### PR TITLE
OMEMO-encrypted MUC logging functionality

### LINKED ISSUE #93: [Conference Logger, OMEMO] Logging in OMEMO-encrypted conferences not working correctly
The Conference Logger plugin does not seem to work with an OMEMO-encrypted MUC/groupchat. It does log messages, but is unable to decrypt them (they decrypted fine when I received them):
psipluslogging

AFAIK Profanity and Gaijim don't support logs of OMEMO-encrypted MUCs either (or at least not out-of-the-box), but the Conversations client for Android does. Are there perhaps any workarounds for this problem (aside from copy+paste by hand)? If not, in theory, could an "OMEMO conference logger" plugin be written? I might try to implement that, but would appreciate it if someone who is familiar with Psi's codebase/api provided some pointers.

### PR DESCRIPTION
**Pull request by kssytsrk**
Fixes #93. The changes have been made to the OMEMO plugin to log messages in groupchats, Conference Logger-style, and to the Conference Logger plugin for it to not log "placeholders" of encrypted messages ("You received a message encrypted with OMEMO but your client doesn't support OMEMO or its support is currently disabled.").

### CODE REVIEW

File: generic/omemoplugin/src/omemoplugin.cpp [hunk 1]
```diff
@@ -330,6 +358,22 @@ bool OMEMOPlugin::encryptMessageElement(int account, QDomElement &message)
         return false;
     }
 
+    // logging functionality for OMEMO-encrypted groupchats
+    if (message.attribute("type") == "groupchat") {
+        QString     room = message.attribute("to");
+        QString     from = m_mucNicks[room];
```
Comment (Ri0n) [inline generic/omemoplugin/src/omemoplugin.cpp:364]:
```
m_mucNicks.value(room)
```
will avoid invalid empty nickname insertion if room is not there. 
Also it may be necessary to do some initialization if it's not there.

Comment (kssytsrk) [reply generic/omemoplugin/src/omemoplugin.cpp:364]: Okay, but wouldn't .value() also return an empty string if the room is not there (unless the second parameter of `defaultValue` is specified, but I'm not sure what kind of default value would be good for this)? Qt docs say so, although I might be misunderstanding it.

Comment (Ri0n) [reply generic/omemoplugin/src/omemoplugin.cpp:364]: It will return empty string. that's correct. 
Since nickname can't be empty, you can check for emptiness and maybe do some initialization if empty.

Imagine a case where you enable OMEMO plugin already after joining. So you missed the initial presence and have to live with this somehow. (drop everything encrypted / force rejoin / ask user what to do)

Comment (kssytsrk) [reply generic/omemoplugin/src/omemoplugin.cpp]: Okay, so I changed the behavior to logging the full jid instead of the nick in case the nick is empty. Would that be fine for now? Can't think of any elegant solution to the problem yet

**Comment by kssytsrk** [comment]
Also, should I add a line into changelog.txt (of OMEMO plugin or/and Conference Plugin) about these changes or are they too minor to mention?

File: generic/omemoplugin/src/omemoplugin.cpp (hunk 1 above)
Comment (Ri0n) [reply generic/omemoplugin/src/omemoplugin.cpp]: yep. should be good for now.
but technically all the MUC info has to be available somewhere in Psi including nicks.

**Comment by Ri0n** [comment]
> Also, should I add a line into changelog.txt (of OMEMO plugin or/and Conference Plugin) about these changes or are they too minor to mention?

please add. you can also bump the plugin version.

**Review by stigger — APPROVED** [review]

**Review by Ri0n — APPROVED** [review]

File: generic/omemoplugin/src/omemoplugin.cpp (hunk 1 above)
Comment (kssytsrk) [reply generic/omemoplugin/src/omemoplugin.cpp]: Well, there is a `mucNicks()` function in ContactInfoAccessingHost, but that just gives a list of nicks from a MUC (without the real jids), so I suppose the `realJid()` function could be ran on each of the nicks until the one associated with the needed account is found... But that would probably be slow, especially if the MUC is big (although I strongly doubt that there exist big OMEMO-encrypted MUCs, as that's very uncomfortable since everyone seems to have to have everyone else in their roster to encrypt all messages). Not sure what other options are there to fix this.

Comment (Ri0n) [reply generic/omemoplugin/src/omemoplugin.cpp]: It's fine to modify plugin interfaces if anything is needed.
We didn't release any stable plugins sdk yet. So it's Ok to change it.
I think after the coming release we can think about some stabilization of the plugins API.

Comment (kssytsrk) [reply generic/omemoplugin/src/omemoplugin.cpp]: Oh, okay. I'll see what can be done, would be great to remove the presence tracking hack as a whole

Comment (Ri0n) [reply generic/omemoplugin/src/omemoplugin.cpp]: Thanks!

**Comment by Neustradamus** [comment]
@kssytsrk: Thanks a lot for your contributions!
